---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: default.score

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - anyOf:
          - group:
              name: BetaUsers
    flagValue: true
